[project]
name = "retail-pipeline"
version = "0.1.0"
description = "Retail Orders, Payments & Loyalty Data Pipeline"
readme = "README.md"
requires-python = ">=3.11"

dependencies = [
    "pandas>=2.0.0",
    "numpy>=1.24.0",
    "pytest>=8.0.0",
    "pandera>=0.20.0"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"